[package]
name = "megadrile"
version = "0.1.0"
authors = ["Oliver Ruebenacker <oliverr@broadinstitute.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
vcf = "0.5.0"
flate2 = "1.0.20"
